### PR TITLE
Change from domains limit to services limit.

### PR DESCRIPTION
**Pull request by bentwire**
**Quality audit reminder**

Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.

Is this the correct wording?

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs`](https://staging.developer.rackspace.com/build-8a1ea90a92/docs/cdn/v1/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-8a1ea90a92/docs/cdn/v1/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs`](https://staging.developer.rackspace.com/build-6bee74cbd8/docs/cdn/v1/)
* [`api-docs`](https://staging.developer.rackspace.com/build-6bee74cbd8/docs/cdn/v1/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs`](https://staging.developer.rackspace.com/build-2dcd36dc49/docs/cdn/v1/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-2dcd36dc49/docs/cdn/v1/)

**Comment by isaacm** [comment]
:+1:

**Comment by cyrichardson** [comment]
This PR is from Mike Panetta. His github user name, bentwire, doesn't show up in our assignees list.

**Pull request merged**
