### PR TITLE
Refactor Rackspace CDN API docs

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs`](https://staging.developer.rackspace.com/build-c0ca3971ab/docs/cdn/v1/developer-guide/)
* [`api-docs`](https://staging.developer.rackspace.com/build-c0ca3971ab/docs/cdn/v1/developer-guide/)

**Comment by cyrichardson** [comment]
Fixes #117

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`internal-api-docs`](https://staging.developer.rackspace.com/build-857a438420/docs/cdn/v1/developer-guide/)
* [`api-docs`](https://staging.developer.rackspace.com/build-857a438420/docs/cdn/v1/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs`](https://staging.developer.rackspace.com/build-32451b2730/docs/cdn/v1/developer-guide/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-32451b2730/docs/cdn/v1/developer-guide/)

**Comment by cyrichardson** [comment]
Closes #117

**Pull request merged**
