### PR TITLE
Standardize required/optional parameter notations in methods in API Ref

### PR DESCRIPTION
**Pull request by cyrichardson**
URI parameters - required is assumed.
query parameters - optional is assumed.
request body parameters - must note if required. If not noted as required, optional is assumed.
response body parameters - no notation.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs`](https://staging.developer.rackspace.com/build-69daf110b9/docs/cdn/v1/developer-guide/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-69daf110b9/docs/cdn/v1/developer-guide/)

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. I just saw this PR and your guidelines for labeling required and optional parameters. We don't have a guideline that is this specific in the style guidelines for parameters (see https://github.com/rackerlabs/docs-rackspace/blob/master/style-guide/m-z-style-guidelines.md#parameters). I'm curious about the source for your required/optional guidelines and whether we ought to add them to the style guide. Thanks!

**Comment by cyrichardson** [comment]
Hi, @kmsholcomb. @catlook had a question from jon perritt about documenting parameters. So this lead to a conversation between @catlook and me about best practices around required/optional notation for parameter descriptions and we came up with the above (because as you note, we don't have anything documented for this specifically). So it seemed that those in my comment seemed to make the most sense to us. 

Please provide any guidance you have for us. Happy to change the above. I added a bit to the comment that might shed a little light on these parameters.

Thanks!

**Comment by kmsholcomb** [comment]
Thanks, @cyrichardson: I think that they make sense. The only question I had was about the request body parameters. Do we label *required* and assume non-labeled parameters are optional, or do we label *optional* and assume that non-labeled parameters are required? I suppose we could go either way, but I also suppose that labeling the required ones as required is the clearer option for the user. That way they never get an error because they didn't know whether a parameter is required. I will add these guidelines to the style guide later today.

(Wow, doing things in GitHub is pretty darn transparent after all. I can butt into almost any discussion now!)

**Comment by cyrichardson** [comment]
@kmsholcomb - For request body parameters, label _required_ and assume non-labeled parameters are optional.
Sounds good about adding to style guidelines. (Sorry, I've never done the alphabetization of parameters... maybe someday we can revisit that...)

Yes, very open in the open world! :-)

**Comment by kmsholcomb** [comment]
To be honest, @cyrichardson, I had forgotten all about the alphabetization guideline, and I'm the one who documented it in the guidelines! We'll make that part of the new "template" that the IA team is creating, and we can all comply after that. :)

**Comment by kmsholcomb** [comment]
@cyrichardson: When you get a chance, would you mind reviewing the updated guidelines in https://github.com/rackerlabs/docs-rackspace/pull/60? If they look good to you, please merge. If not, suggest edits. Thanks!

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks! LGTM!

**Pull request merged**
