### PR TITLE
cdn-v1-20160901

### PR DESCRIPTION
**Pull request by amitgandhinz**
**Quality audit reminder**

Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs`](https://staging.developer.rackspace.com/build-69e76a5cf4/docs/cdn/v1/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-69e76a5cf4/docs/cdn/v1/)

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`internal-api-docs`](https://staging.developer.rackspace.com/build-e4ea955506/docs/cdn/v1/)
* [`api-docs`](https://staging.developer.rackspace.com/build-e4ea955506/docs/cdn/v1/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`api-docs`](https://staging.developer.rackspace.com/build-26a41bbd8d/docs/cdn/v1/)
* [`internal-api-docs`](https://staging.developer.rackspace.com/build-26a41bbd8d/docs/cdn/v1/)

**Comment by rackernexus** [comment]
Your content preview is now ready:

* [`internal-api-docs`](https://staging.developer.rackspace.com/build-8bd14bbf67/docs/cdn/v1/)
* [`api-docs`](https://staging.developer.rackspace.com/build-8bd14bbf67/docs/cdn/v1/)

**Comment by cyrichardson** [comment]
LGTM - merging!

**Pull request merged**
